# Generated by Django 3.0.1 on 2020-01-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('CC', 'CÉDULA DE CIUDADANÍA'), ('CE', 'CÉDULA DE EXTRANJERIA'), ('PS', 'PASAPORTE'), ('NIT', 'NIT')], max_length=50, null=True),
        ),
    ]
