# Generated by Django 3.0.1 on 2020-01-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200104_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(choices=[('medellin', 'Medellin'), ('bogota', 'Bogota'), ('neiva', 'Neiva'), ('cali', 'Cali'), ('cartagena', 'Cartagena'), ('santa marta', 'Santa Marta'), ('ibague', 'Ibague'), ('pereira', 'Pereira'), ('manizales', 'Manizales')], default='Bogota', max_length=50),
        ),
    ]
