# Generated by Django 3.0.1 on 2020-01-04 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200104_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(choices=[('medellin', 'Medellin'), ('bogota', 'Bogota'), ('neiva', 'Neiva'), ('cali', 'Cali'), ('cartagena', 'Cartagena'), ('santa marta', 'Santa Marta'), ('ibague', 'Ibague'), ('pereira', 'Pereira'), ('manizales', 'Manizales')], default='bogota', max_length=50),
        ),
    ]
