# Generated by Django 3.0.1 on 2020-01-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20200104_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='picture',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='picture',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Habitación Individual', 'Habitación Individual'), ('Habitación Doble', 'Habitación Doble'), ('Habitación Doble - 2 Camas', 'Habitación Doble - 2 Camas'), ('Suite', 'Suite')], max_length=30),
        ),
    ]
