# Generated by Django 3.0.1 on 2020-01-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200105_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('last_second_name', models.CharField(max_length=50)),
                ('birthday_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], max_length=50)),
                ('identification_number', models.CharField(max_length=12)),
                ('identification_type', models.CharField(choices=[('CC', 'CÉDULA DE CIUDADANÍA'), ('CE', 'CÉDULA DE EXTRANJERIA'), ('PS', 'PASAPORTE'), ('NIT', 'NIT')], max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
    ]
