# Generated by Django 3.0.1 on 2020-01-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='booking.Reservation', verbose_name='Reservation'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_second_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='second_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
